name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  # ========================== NPM install & node_modules cache ==========================
  Install:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # Checkout parent git repo using CI user's auth token,
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}

      # Configure environment with NodeJS v8
      # See: https://github.com/actions/setup-node
      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12

      # Cache the node_modules based on package-lock hash. Cache is shared across the repo
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - name: Install with npm
        run: npm ci


  # ========================== build ==========================
  Build:
    needs: Install
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Load cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build -- --colors

  # ========================== Unit Tests ==========================
  Test:
    needs: Install
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Load cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Unit Tests
        run: npm run test -- --colors
        env:
          NODE_OPTIONS: --max_old_space_size=4096
